version: '3'

services:
  rabbitmq_example:
    container_name: rabbitmq_example
    image: rabbitmq:3-management
    ports:
      - "5673:5672"
      - "15673:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
volumes:
  rabbitmq-data:
    driver: local